language: python
cache: pip

python:
  - "3.7"
dist: xenial
sudo: false

before_install:
  - python --version

install:
  - pip install -U -r requirements-dev.txt

script:
  - scripts/test.sh

after_success:
  - codecov
