language: python
cache: pip

python:
  - "3.7"
  - "3.8"

dist: xenial
sudo: false

before_install:
  - python --version

install:
  - pip install -U -r requirements-dev.txt

script:
  - scripts/test.sh
  - pre-commit install && pre-commit run --all-files --show-diff-on-failure

after_success:
  - codecov
