from collections import UserDict
from typing import Any

class _Context(UserDict):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def data(self) -> dict: ...
    def exists(self) -> bool: ...
    def copy(self) -> dict: ...

context: _Context
