#!/bin/sh

PYTHON_VERSION_TARGET=3.7.0

set -ex


if which pyenv > /dev/null
then
  echo "Pyenv found"
  pyenv versions | grep -q $PYTHON_VERSION_TARGET || pyenv install $PYTHON_VERSION_TARGET
  pyenv local $PYTHON_VERSION_TARGET
fi

if [ -d venv ]; then rm -r venv; fi
python3 -m venv venv
