#!/bin/sh -e

if [ -d 'venv' ] ; then
  PIP="venv/bin/pip"
else
  PIP="pip"
fi

set -x

ver=$(python3 -V 2>&1 | sed 's/.* \([0-9]\).\([0-9]\).*/\1\2/')
if [ "$ver" -lt "37" ]; then
    echo "This script requires python 3.7 or greater"
    exit 1
fi

"$PIP" install --upgrade pip
"$PIP" install poetry
poetry install
