#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

${PREFIX}poetry run pytest --ignore=example --cov=starlette_context --cov-report=term-missing

if [ -n "$GITHUB_ACTIONS" ]; then
  ${PREFIX}poetry run codecov
fi
