name: Publish to PyPi

on:
  release:
    types:
      - released

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install Python
        run: uv python install
      - name: Build
        run: uv build
      - name: Publish
        run: uv publish --token ${{ secrets.PYPI_RELEASE_STARLETTE_CONTEXT }}
