name: Publish to Test PyPi

on:
  release:
    types:
      - prereleased

jobs:
  publish:
    name: Publish to Test PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Build and publish
        run: uv publish --publish-url https://test.pypi.org/legacy/ --token ${{ secrets.TEST_PYPI_RELEASE_STARLETTE_CONTEXT }}
